### ISSUE TITLE
Расширить блок для ввода исходного кода обработчика события

### ISSUE THREAD

**Issue by Gelezako** [sergejey/majordomo-apiai#3]
Пробовал меня параметы у него
<textarea name="code" id="code" rows=100 cols=200 class="form-control">[#CODE#]</textarea>
видно что размер меняется,а потом снова возвращается к исходному. 
У меня получается достаточно объёмная логика и много строк кода, часто приходится дебажить прямо там. Поле очень маленькое и не удобно искать нужную строчку в коде в таком узком поле. Как его расширить?

**Comment by sergejey** [comment]
F11 -- расширяет на весь экран. В таком режиме можно нажимать Ctrl+S для сохранения.

**Comment by Gelezako** [comment]
работает, спасибо
